### PR TITLE
Update to use micronaut 4

### PR DESCRIPTION
**Pull request by timyates**
- Up version to 3.0.0-SNAPSHOT
- Update to use Gradle 8.1.1
- Use version catalog
- Use core-processor instead of inject
- Fix checkstyle
- Java 17 codestyle
- Move off deprecated method

### CODE REVIEW

**Comment by timyates** [comment]
I think the sonar failure is missing secrets...  But I have no visibility of those, or proof

**Review by melix — APPROVED** [review]

**Comment by melix** [comment]
I'm not sure about sonar: if the token is missing the task shouldn't be executed at all. Maybe it's actually missing the project?

**Comment by timyates** [comment]
> I'm not sure about sonar: if the token is missing the task shouldn't be executed at all. Maybe it's actually missing the project?

Ooooh you could be right... @sdelamo can you create a sonar project for this?

**Comment by sdelamo** [comment]
> > I'm not sure about sonar: if the token is missing the task shouldn't be executed at all. Maybe it's actually missing the project?
> 
> Ooooh you could be right... @sdelamo can you create a sonar project for this?

I have added `micronaut-docs` to sonar.

**Comment by melix** [comment]
Re-running the test to see if it helped.

**Comment by timyates** [comment]
@sdelamo Can you turn off automatic analysis?

> You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.

**Comment by sdelamo** [comment]
> @sdelamo Can you turn off automatic analysis?
> 
> > You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.

I have turned off automatic analysis

**Comment by timyates** [comment]
@sdelamo thank you 👍

**Comment by sdelamo** [comment]
@timyates I have removed myself as reviewer in this PR coordinate with @melix to merge this PR and do a release if need it.

**Comment by timyates** [comment]
@melix AFAICS this is good to merge and release, no?

We only use it in our internal builds, and we set the version in the catalog so should be able to gradually update?

**Comment by melix** [comment]
I merged the PR. I would however refrain on upgrading before we have RCs for Micronaut 4, let's not add random flakiness to our builds.

**Pull request merged**
